if (localStorage.getItem('posts') === null) {
  const posts = [
    {
      id: '1',
      description: 'id = 1',
      createdAt: new Date('2020-03-17T23:00:01'),
      author: 'Lucas Tyber',
      likes: ['user1', 'user2'],
    },
    {
      id: '2',
      description: 'Функции editPost, addPost, deletePost, toggleStatus',
      createdAt: new Date('2020-04-17T23:00:02'),
      author: 'Info',
      photoLink: 'https://www.pressball.by/images/stories/2020/03/20200310231542.jpg',
      likes: ['user1', 'user3'],
    },
    {
      id: '3',
      description: 'id = 3',
      createdAt: new Date('2020-04-17T23:00:00'),
      author: 'qwe',
      photoLink: 'www.com',
      likes: ['user1', 'user12'],
    },
    {
      id: '4',
      description: 'sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text ',
      createdAt: new Date('2020-03-11T23:00:00'),
      author: 'zxcr',
      hashTags: ['animee', '1334'],
      likes: ['user1', 'user123'],
    },
    {
      id: '5',
      description: 'id = 5 ',
      createdAt: new Date('2020-04-16T23:00:00'),
      author: 'zxcr',
      hashTags: ['a', '13371'],
      likes: ['user12', 'user251'],
    },
    {
      id: '6',
      description: 'sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text ',
      createdAt: new Date('2010-03-17T23:00:00'),
      author: 'zxcr',
      likes: ['user11', 'user23'],
    },
    {
      id: '7',
      description: 'sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text ',
      createdAt: new Date('2020-01-17T23:00:00'),
      author: 'zxcr',
      likes: ['user12', 'user23'],
    },
    {
      id: '8',
      description: 'sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text ',
      createdAt: new Date('2020-03-17T21:00:00'),
      author: 'zxcr',
      likes: ['user251', 'user2'],
    },
    {
      id: '9',
      description: 'sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text ',
      createdAt: new Date('2019-03-17T23:00:00'),
      author: 'zxcr',
      likes: ['user1'],
    },
    {
      id: '10',
      description: 'sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text ',
      createdAt: new Date('2020-03-17T23:00:00'),
      author: 'zxcr',
      hashTags: ['anime', '1337'],
      likes: ['user1'],
    },
    {
      id: '11',
      description: 'sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text ',
      createdAt: new Date('2020-04-17T23:00:00'),
      author: 'qwe',
      likes: ['user1'],
    },
    {
      id: '12',
      description: 'sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text ',
      createdAt: new Date('2020-03-17T23:01:00'),
      author: 'zqwe',
      likes: ['user1'],
    },
    {
      id: '13',
      description: 'sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text ',
      createdAt: new Date('2020-03-11T23:01:00'),
      author: 'zxcr',
      hashTags: ['anime', '1337'],
      likes: ['user1'],

    },
    {
      id: '14',
      description: 'sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text ',
      createdAt: new Date('2020-03-15T23:06:00'),
      author: 'zxcr',
      likes: ['user1'],
    },
    {
      id: '15',
      description: 'sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text ',
      createdAt: new Date('2020-03-17T23:16:00'),
      author: 'zxcr',
      likes: ['user1'],
    },
    {
      id: '16',
      description: 'sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text ',
      createdAt: new Date('2020-03-17T23:20:00'),
      author: 'zxcr',
      likes: ['user1'],
    },
    {
      id: '17',
      description: 'sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text ',
      createdAt: new Date('2020-01-17T23:00:00'),
      author: 'zxcr',
      likes: ['user1'],
    },
    {
      id: '18',
      description: 'sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text sample text ',
      createdAt: new Date('2020-02-17T23:00:00'),
      author: 'zxcr',
      likes: ['user1'],
    },
    {
      id: '19',
      description: 'id = 19',
      createdAt: new Date('2020-03-17T23:00:45'),
      author: 'dgsr',
      hashTags: ['anime', '1338'],
      likes: ['user1'],
    },
    {
      id: '20',
      description: 'id = 20',
      createdAt: new Date('2020-03-17T23:00:03'),
      author: 'qwe',
      likes: ['user1'],
    },
  ];
  const strPosts = JSON.stringify(posts);
  localStorage.setItem('posts', strPosts);
}
